### ISSUE TITLE
multiple instances, cluster, support

### ISSUE THREAD

**Issue by peacemakr** [cayasso/primus-rooms#61]
does it work with multiple instances possibly on different hosts? How would it resolve spark ID conflicts (if thats even possible)?

**Comment by fadeenk** [comment]
Hi @peacemakr ,

To answer your question by default no. The reason for that is because the adapter it uses. By default it uses a [memory adapter](https://github.com/cayasso/primus-rooms-adapter) which limits it to a single host.

However the adapter can be switched with another one that allows it to work with multiple hosts. Currently, the only one I know of is the [primus-rooms-redis-adapter](https://github.com/fadeenk/primus-rooms-redis-adapter) which I wrote. 

Hope that this answers your question
